require("plugins.ui")
require("plugins.blink")
require("plugins.lspconfig")
require("plugins.which_key")
require("plugins.transparent")
require("plugins.treesitter")
require("plugins.colorscheme")
require("plugins.tabstatus")
require("plugins.terminal")
require("plugins.fzf")
require("plugins.curl")
require("plugins.cloak")
require("plugins.wakatime")
require("plugins.obsidian")
require("plugins.persistence")
require("plugins.neotest")
-- require("plugins.dap")
require("plugins.lazydev")
