vim.pack.add({
	{ src = "https://github.com/folke/which-key.nvim" },
})

-- local wk = require("which-key")
--
-- wk.setup({
-- 	preset = "helix",
-- 	sort = { "alphanum", "local", "order", "group", "mod" },
-- })
-- wk.add({
-- 	mode = { "n" },
-- 	{ "gs", group = "Surround" },
-- 	{ "gsF", desc = "Find surround (left)" },
-- 	{ "gsd", desc = "Delete Surround" },
-- 	{ "gsa", desc = "Add Surround" },
-- 	{ "gsf", desc = "Find surround (right)" },
-- 	{ "gsh", desc = "Highlight surround" },
-- 	{ "gsn", desc = "Update `n_lines`" },
-- 	{ "gsr", desc = "Replace surround" },
-- })
-- wk.add({
-- 	mode = { "o", "x" },
-- 	-- The 'Around' Group
-- 	{ "a", group = "Around textobject" },
-- 	{ "aa", desc = "Argument" },
-- 	{ "ac", desc = "Call/Invocation" }, -- Your custom 'c'
-- 	{ "af", desc = "Function Definition" }, -- Your custom 'f'
-- 	{ "aq", desc = "Quote" },
-- 	{ "at", desc = "Type/Struct/Class" }, -- Your custom 't'
--
-- 	-- The 'Inside' Group
-- 	{ "i", group = "Inside textobject" },
-- 	{ "ia", desc = "Argument" },
-- 	{ "ic", desc = "Call/Invocation" }, -- Your custom 'c'
-- 	{ "if", desc = "Function Definition" }, -- Your custom 'f'
-- 	{ "iq", desc = "Quote" },
-- 	{ "it", desc = "Type/Struct/Class" }, -- Your custom 't'
-- })
-- vim.keymap.set("n", "<leader>?", function()
-- 	wk.show({ global = true })
-- end, { desc = "Buffer Local keymaps (which-key})" })
